# Generated by Django 5.0 on 2024-11-16 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_topics'),
        ('users', '0003_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='article',
        ),
        migrations.AddField(
            model_name='pin',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PinArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pin')),
            ],
            options={
                'db_table': 'pin_article',
                'unique_together': {('pin', 'article')},
            },
        ),
        migrations.AddField(
            model_name='pin',
            name='articles',
            field=models.ManyToManyField(related_name='pin_articles', through='users.PinArticle', to='articles.article'),
        ),
    ]
