# Generated by Django 5.0 on 2024-11-16 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_pin_article_pin_count_pinarticle_pin_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinarticle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
