# Generated by Django 5.0 on 2024-11-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pinarticle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinarticle',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
