# Generated by Django 4.2 on 2024-11-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='popularity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
