# Generated by Django 5.0 on 2024-09-03 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_comment_article_comments'),
        ('users', '0011_remove_recommendation_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='less_recommend',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='more_recommend',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
            preserve_default=False,
        ),
    ]
