# Generated by Django 5.0 on 2024-09-03 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_comment_article_comments'),
        ('users', '0012_remove_recommendation_less_recommend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='article',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='less_recommend',
            field=models.ManyToManyField(related_name='less_recommend', to='articles.article'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='more_recommend',
            field=models.ManyToManyField(related_name='more_recommend', to='articles.article'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
