# Generated by Django 4.2 on 2024-11-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='popularity',
        ),
    ]
