# Generated by Django 4.2 on 2024-11-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_author'),
        ('users', '0013_remove_customuser_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='authored_by', to='articles.article'),
        ),
    ]
