# Generated by Django 4.2 on 2024-11-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='articles',
        ),
    ]
