# Generated by Django 5.0 on 2024-08-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
    ]
