# Generated by Django 5.0 on 2024-11-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_report_message_remove_report_read_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
