# Generated by Django 5.0 on 2024-11-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_faq_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.AlterModelTable(
            name='faq',
            table=None,
        ),
    ]
