# Generated by Django 5.0 on 2024-11-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_faq_options_alter_faq_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQS'},
        ),
        migrations.AlterModelTable(
            name='faq',
            table='faq',
        ),
    ]
