# Generated by Django 5.0 on 2024-08-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_author_article_topics_topic_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(blank=True, to='articles.topic'),
        ),
    ]
