# Generated by Django 5.0 on 2024-08-27 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_author_alter_article_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
