# Generated by Django 5.0 on 2024-08-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_remove_article_author_article_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topics',
        ),
        migrations.AddField(
            model_name='article',
            name='topic_ids',
            field=models.ManyToManyField(blank=True, related_name='topics', to='articles.topic'),
        ),
    ]
