# Generated by Django 5.0 on 2024-08-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_remove_article_topics_article_topic_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumbnail',
        ),
    ]
