# Generated by Django 4.2 on 2024-11-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('publish', 'Published'), ('draft', 'Draft')], default='draft', max_length=50),
        ),
    ]
