# Generated by Django 5.0 on 2024-09-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_remove_article_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='author',
        ),
    ]
