# Generated by Django 5.0 on 2024-09-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_rename_user_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
