# Generated by Django 5.0 on 2024-09-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_alter_article_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='topics',
            new_name='topic_ids',
        ),
    ]
