# Generated by Django 5.0 on 2024-09-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_rename_topics_article_topic_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='topic_ids',
            new_name='topics',
        ),
    ]
