# Generated by Django 5.0 on 2024-09-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_rename_topic_ids_article_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='topic_ids', to='articles.topic'),
        ),
    ]
