version: "3.9"
services:
  medium_app:
    container_name: medium_app
    restart: always
    volumes:
      - .:/my_code
      # - static_volume:/my_code/staticfiles
    image: medium_app:latest
    build: .
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    depends_on:
      - medium_db_host
      - medium_redis_host
    networks:
      medium_network:

  medium_db_host:
    container_name: medium_db_host
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env.example
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${DB_USER-medium_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD-medium_user_password}
      - POSTGRES_DB=${DB_NAME-medium_db}
    networks:
      - medium_network

  medium_redis_host:
    container_name: medium_redis_host
    image: "redis:7-alpine"
    env_file:
      - .env.example
    expose:
      - "6379"
    restart: always
    networks:
       - medium_network

networks:
  medium_network:
    name: medium_network

# volumes:
#   static_volume:
